# Generated by Django 4.2.3 on 2023-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activepackage",
            name="last_date_of_booking",
            field=models.DateField(),
        ),
    ]
