# Generated by Django 4.2.3 on 2023-07-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_alter_package_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="package",
            new_name="active",
        ),
    ]
