# Generated by Django 4.2.3 on 2023-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_rename_package_request_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="activepackage",
            name="vacancies",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
