# Generated by Django 4.2.3 on 2023-07-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0006_activepackage_vacancies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activepackage",
            name="vacancies",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
