# Generated by Django 4.2.3 on 2023-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0008_alter_activepackage_vacancies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activepackage",
            name="vacancies",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
